import Head from 'next/head';
import classes from '../styles/Home.module.scss';
import { Navbar } from '../components';

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Beyond Looks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <h1 className={classes.title}>
          Welcome 宋珮瑶！
        </h1>

      </main>
    </div>
  )
}
